# Auto-generated by Cimas: Do not edit it manually!
# See https://github.com/metanorma/cimas
#!make
ifeq ($(OS),Windows_NT)
SHELL := pwsh -NoProfile
RM    := Remove-Item -Force
else
SHELL := /bin/bash
RM    := rm -f
endif

SRC := $(wildcard views/*.lutaml)

ifeq ($(SRC),)
SRC := $(patsubst models/%.wsd,views/%.lutaml,$(wildcard models/*.wsd))
endif

PNG := $(patsubst views/%.lutaml,images/%.png,$(SRC))

all: $(PNG)

images/%.png: views/%.lutaml | images
	lutaml lml generate -t png -o $@ $<

views/%.lutaml: models/%.wsd | views
	lutaml-wsd2uml $< > $@

views:
	mkdir views

images:
	mkdir images

clean:
	-$(RM) images/*.png

# ── Validation targets ──────────────────────────────────────────────────
# Run all schema/model/ontology drift checks. Mirrors what CI runs in
# .github/workflows/validate-schemas.yml. All validators are pure Ruby
# (lib/glossarist/concept_model/) invoked through the exe/ shims.

BUNDLE := bundle exec

validate: validate-ontologies validate-examples validate-negative-examples \
          check-enum-drift check-jsonld-context check-shacl-coverage \
          check-lutaml-references check-partitive-relation-coherence \
          check-external-concept-shape check-binary-has-part-redundancy
	@echo "All validation checks passed."

validate-ontologies:
	$(BUNDLE) exe/validate-ontologies

validate-examples:
	$(BUNDLE) exe/validate-examples

validate-negative-examples:
	$(BUNDLE) exe/validate-negative-examples

check-enum-drift:
	$(BUNDLE) exe/check-enum-drift

check-jsonld-context:
	$(BUNDLE) exe/check-jsonld-context

check-shacl-coverage:
	$(BUNDLE) exe/check-shacl-coverage

check-lutaml-references:
	$(BUNDLE) exe/check-lutaml-references

check-partitive-relation-coherence:
	$(BUNDLE) exe/check-partitive-relation-coherence

check-external-concept-shape:
	$(BUNDLE) exe/check-external-concept-shape

check-binary-has-part-redundancy:
	$(BUNDLE) exe/check-binary-has-part-redundancy

validate-scripts:
	$(BUNDLE) rspec spec/ --format documentation

.PHONY: clean validate validate-ontologies validate-examples \
        validate-negative-examples check-enum-drift check-jsonld-context \
        check-shacl-coverage check-lutaml-references \
        check-partitive-relation-coherence check-external-concept-shape \
        check-binary-has-part-redundancy validate-scripts
