@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************

'Review Indicator	<empty field> or 'Under Review in Source Document'
'Date Accepted	yyyy-mm-dd
'Date Amended	yyyy-mm-dd
'Review Date	yyyy-mm-dd
'Review Status	pending', 'tentative', 'final'
'Review Type	supersession', 'retirement'
'Review Decision	withdrawn', 'accepted', 'notAccepted'
'Review Decision Date	yyyy-mm-dd
'Review Decision Event	String
'Review Decision Notes	String
'Glossary Release	"release1' = 1, 'release1_retired' = -1, 'release2' = 2, release2_retired' = -2 etc"

class Definition <<BasicDocument>>{
}


'******* CLASS RELATIONS **********************************************
Concept <-- ConceptSource
Concept <-- Definition
Concept <-- Designation
Concept <-- RelatedConcept
Concept <-- NonVerbRep
Concept <-- GlossaristDefinition

ConceptSource <-- ConceptSourceStatus
ConceptSource <-- ConceptSourceType

RelatedConcept <-- RelatedConceptType

@enduml

