@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************

enum Iso639ThreeCharCode {
}
enum Iso3166Code {
}
enum Iso15924Code {
}

class TextElement <<BasicDocument>> {
}

class GlossaristTextElement {
}

class EmptySlot {
}

class TextElementType <<BasicDocument>> {
}

class GlossaristTextElementType {
  +elements: GlossaristTextElement[0..1]
}

Designation <-- NormativeStatus

ExpressionDesignation <-- GrammarInfo

AbbreviationDesignation <-- AbbreviationType

GrammarInfo <-- GrammarGender

TextElementType <|-- GlossaristTextElementType

ExpressionDesignation <-- GlossaristTextElementType
GlossaristTextElement <|-- TextElement
GlossaristTextElement <|-- EmptySlot
GlossaristTextElementType <-- GlossaristTextElement

@enduml

