@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************

RelatedConcept <-- RelatedConceptType
ConceptDate <-- ConceptDateType
ManagedConcept <-- RelatedConcept
ManagedConcept <-- ConceptStatus
ManagedConcept <-- ConceptDate
ManagedConcept <-- LocalizedConcept

ManagedConceptCollection <-- ManagedConcept

@enduml
