@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class ConceptCollection {
  +concepts: Concept[0..*]
}

@enduml
