@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class Concept {
  +id: String[0..1]
  +designations: Designation[1..*]
  +domain: <<BasicDocument>> LocalizedString[0..1]
  +subject: <<BasicDocument>> LocalizedString[0..1]
  +usageInfo: <<BasicDocument>> LocalizedString[0..1]
  +definition: <<BasicDocument>> Definition[1..*]
  +notes: <<BasicDocument>> ParagraphBlock[0..*]
  +examples: <<BasicDocument>> ParagraphBlock[0..*]
  +sources: ConceptSource[0..*]
  +related: RelatedConcept[0..*]
}

'Review Indicator	<empty field> or 'Under Review in Source Document'
'Date Accepted	yyyy-mm-dd
'Date Amended	yyyy-mm-dd
'Review Date	yyyy-mm-dd
'Review Status	pending', 'tentative', 'final'
'Review Type	supersession', 'retirement'
'Review Decision	withdrawn', 'accepted', 'notAccepted'
'Review Decision Date	yyyy-mm-dd
'Review Decision Event	String
'Review Decision Notes	String
'Glossary Release	"release1' = 1, 'release1_retired' = -1, 'release2' = 2, release2_retired' = -2 etc"


class ConceptSource {
  +status: ConceptSourceStatus
  +type: ConceptSourceType
  +origin: <<Bibliography>> Citation
  +modification: <<BasicDocument>> ParagraphBlock[0..1]
}

class Definition <<BasicDocument>>{
}

enum ConceptSourceType {
  authoritative
  lineage
}

enum ConceptSourceStatus {
  identical
  modified
  restyled
  context-added
  generalisation
  specialisation
  unspecified
}

class RelatedConcept {
  +type: RelatedConceptType
  +content: <<BasicDocument>> LocalizedString
}

enum RelatedConceptType {
  deprecates
  supersedes
  narrower
  broader
  equivalent
  compare
  contrast
  see
}

'******* CLASS RELATIONS **********************************************
Concept <-- ConceptSource
Concept <-- Definition
Concept <-- Designation
Concept <-- RelatedConcept

ConceptSource <-- ConceptSourceStatus
ConceptSource <-- ConceptSourceType

RelatedConcept <-- RelatedConceptType

@enduml

