@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class Designation {
  +normativeStatus: NormativeStatus
  +geographicArea: Iso3166Code[0..*]
}

class ExpressionDesignation {
  +text: <<BasicDocument>> LocalizedString
  +language: Iso639ThreeCharCode
  +script: Iso15924Code[0..1]
  +pronunciation: <<BasicDocument>> LocalizedString[0..*]
  +grammarInfo: GrammarInfo[0..1]
}

class SymbolDesignation {
  +isInternational: Boolean[0..1]
}

class PrefixDesignation {
}

class SuffixDesignation {
}

class AbbreviationDesignation {
}

class AcronymDesignation {
  +isInternational: Boolean[0..1]
}

class LetterSymbolDesignation {
  +text: <<BasicDocument>> LocalizedString
  +language: Iso639ThreeCharCode
  +script: Iso15924Code[0..1]
}

class GraphicalSymbolDesignation {
  +text: <<BasicDocument>> LocalizedString[0..1]
  +image: Image[0..1]
  +isInternational: Boolean[0..1]
}

enum NormativeStatus {
  preferred
  admitted
  deprecated
}

class GrammarInfo {
  +gender: DesignationGender[0..*]
  +isPreposition: Boolean[0..1]
  +isParticiple: Boolean[0..1]
  +isAdjective: Boolean[0..1]
  +isVerb: Boolean[0..1]
  +isAdverb: Boolean[0..1]
  +isNoun: Boolean[0..1]
}

enum GrammarGender {
  masculine
  feminine
  neuter
  common
}

enum Iso639ThreeCharCode {
}
enum Iso3166Code {
}
enum Iso15924Code {
}

Designation <|-left- ExpressionDesignation
Designation <|-- SymbolDesignation
Designation <-- NormativeStatus

ExpressionDesignation <|-- PrefixDesignation
ExpressionDesignation <|-- SuffixDesignation
ExpressionDesignation <|-- AbbreviationDesignation
ExpressionDesignation <|-- AcronymDesignation
ExpressionDesignation <-- GrammarInfo

SymbolDesignation <|-- LetterSymbolDesignation
SymbolDesignation <|-- GraphicalSymbolDesignation

GrammarInfo <-- GrammarGender

@enduml

