@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class Designation {
  +text: <<BasicDocument>> LocalizedString
  +type: DesignationType
  +grammarInfo: GrammarInfo[0..1]
  +normativeStatus: NormativeStatus
  +pronunciation: <<BasicDocument>> LocalizedString[0..*]

  +domain: <<BasicDocument>> LocalizedString[0..1]
  +subject: <<BasicDocument>> LocalizedString[0..1]
  +usageInfo: <<BasicDocument>> LocalizedString[0..1]

  +language: Iso639ThreeCharCode
  +script: Iso15924Code[0..1]
  +geographicArea: Iso3166Code[0..*]
  +isInternational: Boolean[0..1]
}

enum NormativeStatus {
  preferred
  admitted
  deprecated
}

enum DesignationType {
  expression
  symbol
  prefix
  suffix
  abbreviation
  acronym
}

class GrammarInfo {
  +gender: DesignationGender[0..1]
  +isPreposition: Boolean[0..1]
  +isParticiple: Boolean[0..1]
}

enum GrammarGender {
  masculine
  feminine
  neuter
  common
}

class GrammarNoun {
}

class GrammarAdjective {
}

class GrammarVerb {
}

class GrammarAdverb {
}

enum Iso639ThreeCharCode {
}
enum Iso3166Code {
}
enum Iso15924Code {
}

Designation <-- GrammarInfo
Designation <-- NormativeStatus
Designation <-- DesignationType
Designation <-- Iso639ThreeCharCode
Designation <-- Iso3166Code
Designation <-- Iso15924Code

GrammarInfo <|-- GrammarNoun
GrammarInfo <|-- GrammarAdjective
GrammarInfo <|-- GrammarVerb
GrammarInfo <|-- GrammarAdverb
GrammarInfo <-- GrammarGender

@enduml

