@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class Designation {
  +normativeStatus: NormativeStatus
  +geographicArea: Iso3166Code[0..*]
}

class ExpressionDesignation {
  +text: <<BasicDocument>> LocalizedString
  +language: Iso639ThreeCharCode
  +script: Iso15924Code[0..1]
  +pronunciation: <<BasicDocument>> LocalizedString[0..*]
  +grammarInfo: GrammarInfo[0..1]
  +pronunciation: <<BasicDocument>> LocalizedString[0..*]
}

class SymbolDesignation {
  +isInternational: Boolean[0..1]
}

class PrefixDesignation {
}

class SuffixDesignation {
}

class AbbreviationDesignation {
}

class AcronymDesignation {
  +isInternational: Boolean[0..1]
}

class LetterSymbolDesignation {
  +text: <<BasicDocument>> LocalizedString
  +language: Iso639ThreeCharCode
  +script: Iso15924Code[0..1]
}

class GraphicalSymbolDesignation {
  +text: <<BasicDocument>> LocalizedString[0..1]
  +image: Image[0..1]
  +isInternational: Boolean[0..1]
}

enum NormativeStatus {
  preferred
  admitted
  deprecated
}

class GrammarInfo {
  +gender: DesignationGender[0..1]
  +isPreposition: Boolean[0..1]
  +isParticiple: Boolean[0..1]
}

enum GrammarGender {
  masculine
  feminine
  neuter
  common
}

class GrammarNoun {
}

class GrammarAdjective {
}

class GrammarVerb {
}

class GrammarAdverb {
}

enum Iso639ThreeCharCode {
}
enum Iso3166Code {
}
enum Iso15924Code {
}

Designation <|-- ExpressionDesignation
Designation <|-- SymbolDesignation
Designation <-- NormativeStatus
Designation <-- Iso3166Code

ExpressionDesignation <|-- PrefixDesignation
ExpressionDesignation <|-- SuffixDesignation
ExpressionDesignation <|-- AbbreviationDesignation
ExpressionDesignation <|-- AcronymDesignation
ExpressionDesignation <-- Iso639ThreeCharCode
ExpressionDesignation <-- Iso15924Code
ExpressionDesignation <-- GrammarInfo

SymbolDesignation <|-- LetterSymbolDesignation
SymbolDesignation <|-- GraphicalSymbolDesignation
LetterSymbolDesignation <-- Iso15924Code
LetterSymbolDesignation <-- Iso639ThreeCharCode

GrammarInfo <|-- GrammarNoun
GrammarInfo <|-- GrammarAdjective
GrammarInfo <|-- GrammarVerb
GrammarInfo <|-- GrammarAdverb
GrammarInfo <-- GrammarGender

@enduml

