@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

'******* CLASS DEFINITION *********************************************
class ManagedConceptCollection {
  +concepts: ManagedConcept[0..*]
}

class ManagedConcept {
  +related: RelatedConcept[0..*]
  +status: ConceptStatus
  +dates: ConceptDate[0..*]
  +localizedConcepts: LocalizedConcept[1..*]
}

class LocalizedConcept {
  +language: Iso639ThreeCharCode
  +script: Iso15924Code[0..1]
  +concept: Concept
}

enum ConceptStatus{
  draft
  notValid
  valid
  superseded
  retired
}

class ConceptDate {
  +date: Iso8601Date
  +type: ConceptDateType
}

enum ConceptDateType {
  accepted
  amended
  retired
}

RelatedConcept <-- RelatedConceptType
ConceptDate <-- ConceptDateType
Concept <|-- LocalizedConcept
ManagedConcept <-- RelatedConcept
ManagedConcept <-- ConceptStatus
ManagedConcept <-- ConceptDate
ManagedConcept <-- LocalizedConcept

ManagedConceptCollection <-- ManagedConcept

@enduml
